# Generated by Django 5.0.6 on 2024-06-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_feed_company_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='alias',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='town',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
